version: "3"

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=pglocal
      - POSTGRES_PASSWORD=pg123
      - POSTGRES_DB=riderize
      - POSTGRES_HOST=db
  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  riderize-rest:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - HOST_DOCKER_INTERNAL=http://host.docker.internal
