version: "3"

services:
  riderize-rest:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/London
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  build:
    context: backend-test
    dockerfile: Dockerfile
