version: "3"

services:
  riderize-rest:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=5432:5432
      - TZ=Europe/London
    network_mode: "host"
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    network_mode: "host"
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    environment:
      - REDIS_HOST=6379:6379
      - REDIS_PORT=${REDIS_PORT}
