version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pglocal
      - POSTGRES_PASSWORD=pg123
      - POSTGRES_DB=riderize
      - POSTGRES_HOST=db
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

  riderize-rest:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
