version: "3"

services:
  riderize-rest:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/London
  redis:
    image: redis
    container_name: redis
    hostname: localhost
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_HOST=redis
    ports:
      - 6379:6379
